import { removeUndefinedProperties } from '../util.js';


export const buildOxlintConfig = (inputParams = {}) => {
  const defaultParams = {
  };

  const params = { ...defaultParams, ...removeUndefinedProperties(inputParams) };
  const config = {
    plugins: [
      'typescript',
      'react',
      'jsx-a11y',
      'import',
    ],
    categories: {
      correctness: 'off',
    },
    env: {
      builtin: true,
      browser: true,
      node: true,
    },
    globals: {
      myCustomGlobal: 'readonly',
    },
    settings: {
      react: {
        version: '19',
      },
    },
    ignorePatterns: [
      '**/node_modules/**/*',
      '**/build/**/*',
      '**/dist/**/*',
      '**/dist-ssr/**/*',
      '**/public/**/*',
    ],
    rules: {
      // Correctness (from eslint recommended)
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': ['error', { allowShortCircuit: false, allowTernary: false, allowTaggedTemplates: false }],

      // Unused vars/imports (replaces eslint-plugin-unused-imports)
      'no-unused-vars': ['error', {
        vars: 'all',
        varsIgnorePattern: '^_',
        args: 'after-used',
        argsIgnorePattern: '^_',
      }],

      'no-shadow': 'error',

      // Core best practices (from airbnb, ported where oxlint has an equivalent)
      'array-callback-return': ['error', { allowImplicit: true }],
      'block-scoped-var': 'error',
      'class-methods-use-this': 'error',
      curly: ['error', 'multi-line'],
      'default-case': ['error', { commentPattern: '^no default$' }],
      'default-case-last': 'error',
      'default-param-last': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'no-alert': 'warn',
      'no-await-in-loop': 'error',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-console': ['error', { allow: ['error', 'warn'] }],
      'no-constructor-return': 'error',
      'no-continue': 'error',
      'no-else-return': ['error', { allowElseIf: false }],
      'no-empty-function': ['error', { allow: ['arrowFunctions', 'functions', 'methods'] }],
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loop-func': 'error',
      'no-multi-assign': ['error'],
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-param-reassign': ['error', {
        props: true,
        ignorePropertyModificationsFor: [
          'acc', 'accumulator', 'e', 'ctx', 'context',
          'req', 'request', 'res', 'response', '$scope', 'staticContext',
        ],
      }],
      'no-plusplus': 'error',
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-restricted-globals': ['error',
        { name: 'isFinite', message: 'Use Number.isFinite instead.' },
        { name: 'isNaN', message: 'Use Number.isNaN instead.' },
        'addEventListener', 'blur', 'close', 'closed', 'confirm', 'defaultStatus',
        'defaultstatus', 'event', 'external', 'find', 'focus', 'frameElement',
        'frames', 'history', 'innerHeight', 'innerWidth', 'length', 'location',
        'locationbar', 'menubar', 'moveBy', 'moveTo', 'name', 'onblur', 'onerror',
        'onfocus', 'onload', 'onresize', 'onunload', 'open', 'opener', 'opera',
        'outerHeight', 'outerWidth', 'pageXOffset', 'pageYOffset', 'parent', 'print',
        'removeEventListener', 'resizeBy', 'resizeTo', 'screen', 'screenLeft',
        'screenTop', 'screenX', 'screenY', 'scroll', 'scrollbars', 'scrollBy',
        'scrollTo', 'scrollX', 'scrollY', 'self', 'status', 'statusbar', 'stop',
        'toolbar', 'top',
      ],
      'no-restricted-properties': ['error',
        { object: 'arguments', property: 'callee', message: 'arguments.callee is deprecated' },
        { object: 'global', property: 'isFinite', message: 'Please use Number.isFinite instead' },
        { object: 'self', property: 'isFinite', message: 'Please use Number.isFinite instead' },
        { object: 'window', property: 'isFinite', message: 'Please use Number.isFinite instead' },
        { object: 'global', property: 'isNaN', message: 'Please use Number.isNaN instead' },
        { object: 'self', property: 'isNaN', message: 'Please use Number.isNaN instead' },
        { object: 'window', property: 'isNaN', message: 'Please use Number.isNaN instead' },
        { property: '__defineGetter__', message: 'Please use Object.defineProperty instead.' },
        { property: '__defineSetter__', message: 'Please use Object.defineProperty instead.' },
        { object: 'Math', property: 'pow', message: 'Use the exponentiation operator (**) instead.' },
      ],
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'object-shorthand': ['error', 'always', { ignoreConstructors: false, avoidQuotes: true }],
      'prefer-arrow-callback': ['error', { allowNamedFunctions: false, allowUnboundThis: true }],
      'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: true }],
      'prefer-exponentiation-operator': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
      'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      radix: 'error',
      'symbol-description': 'error',
      yoda: 'error',
      'no-underscore-dangle': ['error', { allow: ['__filename', '__dirname'] }],

      // Import rules
      'import/first': 'error',
      'import/newline-after-import': 'error',
      'import/no-absolute-path': 'error',
      'import/no-amd': 'error',
      'import/no-cycle': 'error',
      'import/no-dynamic-require': 'error',
      'import/no-duplicates': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-self-import': 'error',
      'import/no-webpack-loader-syntax': 'error',
      // NOTE: import/order and sort-imports are intentionally not ported here - use oxfmt's `sortImports` instead

      // React rules
      'react/self-closing-comp': ['error', { component: true, html: true }],
      'react/jsx-filename-extension': ['warn', { extensions: ['.tsx', '.jsx'] }],
      'react/jsx-boolean-value': ['warn', 'always'],
      'react/jsx-fragments': ['warn', 'element'],
      'react/button-has-type': 'error',
      'react/jsx-no-constructed-context-values': 'error',
      'react/jsx-props-no-spreading': 'error',
      'react/jsx-no-script-url': 'error',
      'react/jsx-pascal-case': ['error', { allowAllCaps: true, ignore: [] }],
      'react/no-array-index-key': 'error',
      'react/no-unstable-nested-components': 'error',
      'react/style-prop-object': 'error',
      'react/void-dom-elements-no-children': 'error',
      'react/display-name': 'error',
      'react/jsx-key': 'error',
      'react/jsx-no-comment-textnodes': 'error',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-target-blank': 'error',
      'react/jsx-no-undef': 'error',
      'react/no-children-prop': 'error',
      'react/no-danger-with-children': 'error',
      'react/no-direct-mutation-state': 'error',
      'react/no-find-dom-node': 'error',
      'react/no-is-mounted': 'error',
      'react/no-render-return-value': 'error',
      'react/no-string-refs': 'error',
      'react/no-unescaped-entities': 'error',
      'react/no-unknown-property': 'error',
      'react/rules-of-hooks': 'error',
      'react/exhaustive-deps': 'error',

      // jsx-a11y overrides
      'jsx-a11y/anchor-is-valid': 'off',

      // TypeScript
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': ['error', { allowInterfaces: 'always' }],
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      // NOTE: no-explicit-any was in the migrated recommended set but isn't in our previous eslint config, so it's left off
      'typescript/no-explicit-any': 'off',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-with': 'off',
        },
      },
      {
        files: ['**/*.stories.tsx', '**/*.stories.jsx', '.storybook/**/*'],
        rules: {
          'react/jsx-props-no-spreading': 'off',
          'react/no-array-index-key': 'off',
          'no-alert': 'off',
          'no-console': 'off',
        },
      },
    ],
  };
  if (params.configModifier) {
    return params.configModifier(config);
  }
  return config;
};
